apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: magicmirror
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: hive.ak-online.be
    path: "/volumes/k8s/magic-mirror"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: magicmirror
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
