apiVersion: v1
kind: Service
metadata:
  labels:
    app: xl-mm
  name: xl-mm
  namespace: magicmirror
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: xl-mm
  sessionAffinity: None
  type: LoadBalancer
