name: Docker

on:
  push:
  pull_request:
  schedule:
    - cron: "17 3 * * *"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        id: docker-login
        if: success() && github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and Push
        if: steps.docker-login.outcome == 'success'
        run: ./build.sh "--push"
      - name: Docker Build
        if: steps.docker-login.outcome == 'skipped'
        run: ./build.sh
